### ISSUE TITLE
Youtube channel promoting project possibly run by bots

### ISSUE THREAD

**Issue by Cydget** [BusKill/buskill-app#84]
I think you have a issue where someone is trying to use this github project to scam users. https://www.youtube.com/@buskill
The channel auto deletes comments calling out the existing magnetic usb c breakaway adapters that could be bought for < 5$ online leading me to believe that the channel is run by bots as there was no link to this github page, but many links to various store pages. 

If its is not run by bots, then the channel is deceptive/ practicing in anticompetitive behavior that misleads people in bad faith.

**Comment by maltfield** [comment]
@Cydget  Did you send us the right link?

Scroll to the bottom of our official website (https://buskill.in) and you'll see a link to our official youtube channel (https://www.youtube.com/channel/UC5Njxb027m2OmrocrH33oew/about), which I believe is the same as the one you linked-to (https://www.youtube.com/@buskill)

> The channel auto deletes comments calling out the existing magnetic usb c breakaway adapters that could be bought for < 5$ online leading me to believe that the channel is run by bots as there was no link to this github page, but many links to various store pages.

If there's any auto-deleting happening, then it's Google.

We explicitly provide links in our official documentation to usb-c magnetic breakaways in the Hardware Developer guide here:

 * https://docs.buskill.in/buskill-app/en/stable/hardware_dev/bom.html

> If its is not run by bots, then the channel is deceptive/ practicing in anticompetitive behavior that misleads people in bad faith.

I'm definitely not a bot, and we don't get many comments. Perhaps YouTube is deleting them and that's why? The only comment that I've deleted myself was an advertisement for some marketing company (trying to get us to use their product to increase YouTube views).

**Comment by maltfield** [comment]
I'm not a big fan of YouTube in-general. I would be open to using PeerTube or something, if we could find an instance that's not going to disappear in a few years..

**Comment by Cydget** [comment]
Sorry, may have jumped to the wrong conclusions(thanks youtube for deleting my comments). I saw the github link in the description on video https://www.youtube.com/watch?v=vFTQatw94VU&t=4s to Melanie Allen's page and got a page does not exist when following it leading me to think that the channel was intentionally not directing to the official github project, and was possible just reuploading your content on a bot account for views/redirects. ( low channel subscriber count when the github project has many starts made me think it was a channel reupload bot as well) . I apologize

**Comment by maltfield** [comment]
No worries. I'm not very good at video production, so we haven't posted many videos.

But, you know, subscribe and tell your friends to subscribe so we can get that count up ;)
